#%RAML 1.0 DataType

type: object
properties: 
  hotelID: integer
  name: string
  hotelType: string
  price: integer
  roomsAvailable: integer
  city: string
  cityCode: string
  state: string
  pincode: integer