#%RAML 1.0 NamedExample
value:
  -
    hotelID: 2
    name: Capitol
    hotelType: 3 Star
    price: 2980
    roomsAvailable: 55
    city: Yeshwanthpur
    cityCode: YPR
    state: Karnataka
    pincode: 560022
    
  -
    hotelID: 3
    name: Movenpick
    hotelType: 4 Star
    price: 4500
    roomsAvailable: 5
    city: Yeshwanthpur
    cityCode: YPR
    state: Karnataka
    pincode: 560022
    