#%RAML 1.0 NamedExample
value:

  - 
    CabID: 1
    DriverName: Amit
    CabType: Micro
    ProviderName: Ola
    ServingLocation: Bangalore
    isBooked: true
    CabNumber: KA-08-A-0339
      
  - 
    CabID: 2
    DriverName: Shankar
    CabType: Sedan
    ProviderName: Ola
    ServingLocation: Bangalore
    isBooked: true
    CabNumber: KA-08-A-0859
  
  - 
    CabID: 2
    DriverName: Ravi
    CabType: SUV
    ProviderName: Meru
    ServingLocation: Yeswanthpur
    isBooked: true
    CabNumber: KA-08-A-0859
