#%RAML 1.0 NamedExample
value:

  - 
    flightID: 1 
    airline: Indigo
    price: 4900
    seatsAvailable: 165
    departureDate: 29-11-2021
    source: JAI
    destination: BLR
    planeType: Boeing 767 
      
  - 
    flightID: 2
    airline: Indigo
    price: 8540
    seatsAvailable: 24
    departureDate: 25-11-2021
    source: JAI
    destination: BLR
    planeType: Airbus 320
